name: Git pull en App Tier
run-name: ${{ github.actor }} actualizó el repositorio App Tier. 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: cat ssh-keyscan -H ${{ secrets.SSH_HOST }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Execute script
        run: ssh root@${{ secrets.SSH_HOST }} 'cd /home/azureuser/apptier2019 && sudo git reset --hard origin/master && npm i && node create_env.js && pm2 restart server'